import { Request, Response } from "express";
import { prisma } from "../prisma/client";
import ExcelJS from "exceljs";

function addMeta(sheet: ExcelJS.Worksheet, adminId: number) {
  sheet.insertRow(1, [
    `Admin System Export | Generated By Admin ID: ${adminId} | Generated At: ${new Date().toLocaleString(
      "en-IN",
    )}`,
  ]);

  sheet.mergeCells("A1:L1");
  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).alignment = { vertical: "middle", horizontal: "center" };
}

function styleHeader(sheet: ExcelJS.Worksheet) {
  const headerRow = sheet.getRow(2);
  headerRow.font = { bold: true };
  headerRow.alignment = { vertical: "middle", horizontal: "center" };
}

export async function exportAdminExcel(req: Request, res: Response) {
  try {
    const adminId = req.user!.sub;

    const workbook = new ExcelJS.Workbook();
    workbook.creator = "QuickConcession System";
    workbook.created = new Date();

    const studentSelect = {
      id: true,
      enrollmentNo: true,
      fullName: true,
      email: true,
      mobileNumber: true,
      course: true,
      year: true,
      sem: true,
      shift: true,
      active: true,
      isDeleted: true,
      createdAt: true,
    } as const;

    const allStudents = await prisma.student.findMany({
      orderBy: { id: "asc" },
      select: studentSelect,
    });

    const deletedStudents = await prisma.student.findMany({
      where: { isDeleted: true },
      orderBy: { id: "asc" },
      select: studentSelect,
    });

    const studentSheet = workbook.addWorksheet("All Students");
    studentSheet.columns = [
      { header: "ID", key: "id", width: 8 },
      { header: "Enrollment No", key: "enrollmentNo", width: 18 },
      { header: "Full Name", key: "fullName", width: 22 },
      { header: "Email", key: "email", width: 25 },
      { header: "Mobile", key: "mobileNumber", width: 15 },
      { header: "Course", key: "course", width: 15 },
      { header: "Year", key: "year", width: 10 },
      { header: "Semester", key: "sem", width: 10 },
      { header: "Shift", key: "shift", width: 10 },
      { header: "Active", key: "active", width: 10 },
      { header: "Created At", key: "createdAt", width: 20 },
    ];

    addMeta(studentSheet, adminId);
    studentSheet.views = [{ state: "frozen", ySplit: 2 }];
    styleHeader(studentSheet);

    allStudents
      .filter((s) => !s.isDeleted)
      .forEach((s) => {
        studentSheet.addRow({
          ...s,
          createdAt: s.createdAt.toLocaleDateString("en-IN"),
        });
      });

    studentSheet.addRow({});
    studentSheet.addRow({
      enrollmentNo: "TOTAL STUDENTS",
      fullName: allStudents.filter((s) => !s.isDeleted).length,
    });

    const deletedStudentSheet = workbook.addWorksheet("Deleted Students");
    deletedStudentSheet.columns = studentSheet.columns;

    addMeta(deletedStudentSheet, adminId);
    deletedStudentSheet.views = [{ state: "frozen", ySplit: 2 }];
    styleHeader(deletedStudentSheet);

    deletedStudents.forEach((s) => {
      deletedStudentSheet.addRow({
        ...s,
        createdAt: s.createdAt.toLocaleDateString("en-IN"),
      });
    });

    deletedStudentSheet.addRow({});
    deletedStudentSheet.addRow({
      enrollmentNo: "TOTAL DELETED",
      fullName: deletedStudents.length,
    });

    const staffSelect = {
      id: true,
      fullName: true,
      email: true,
      role: true,
      active: true,
      isDeleted: true,
      createdAt: true,
    } as const;

    const allStaff = await prisma.staff.findMany({
      orderBy: { id: "asc" },
      select: staffSelect,
    });

    const deletedStaff = await prisma.staff.findMany({
      where: { isDeleted: true },
      orderBy: { id: "asc" },
      select: staffSelect,
    });

    const staffSheet = workbook.addWorksheet("All Staff");
    staffSheet.columns = [
      { header: "ID", key: "id", width: 8 },
      { header: "Full Name", key: "fullName", width: 22 },
      { header: "Email", key: "email", width: 25 },
      { header: "Role", key: "role", width: 15 },
      { header: "Active", key: "active", width: 10 },
      { header: "Created At", key: "createdAt", width: 20 },
    ];

    addMeta(staffSheet, adminId);
    staffSheet.views = [{ state: "frozen", ySplit: 2 }];
    styleHeader(staffSheet);

    allStaff
      .filter((s) => !s.isDeleted)
      .forEach((s) => {
        staffSheet.addRow({
          ...s,
          createdAt: s.createdAt.toLocaleDateString("en-IN"),
        });
      });

    staffSheet.addRow({});
    staffSheet.addRow({
      fullName: "TOTAL STAFF",
      email: allStaff.filter((s) => !s.isDeleted).length,
    });

    const deletedStaffSheet = workbook.addWorksheet("Deleted Staff");
    deletedStaffSheet.columns = staffSheet.columns;

    addMeta(deletedStaffSheet, adminId);
    deletedStaffSheet.views = [{ state: "frozen", ySplit: 2 }];
    styleHeader(deletedStaffSheet);

    deletedStaff.forEach((s) => {
      deletedStaffSheet.addRow({
        ...s,
        createdAt: s.createdAt.toLocaleDateString("en-IN"),
      });
    });

    deletedStaffSheet.addRow({});
    deletedStaffSheet.addRow({
      fullName: "TOTAL DELETED",
      email: deletedStaff.length,
    });

    const buffer = await workbook.xlsx.writeBuffer();

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=admin-system-export.xlsx",
    );

    res.setHeader("Content-Length", buffer.byteLength);

    res.status(200).send(buffer);
  } catch (error) {
    console.error("Admin export error:", error);
    res.status(500).json({ message: "Failed to export admin data" });
  }
}
